CREATE ROLE PROFESSORES NOCREATEDB NOCREATEROLE INHERIT NOLOGIN NOBYPASSRLS CONNECTION LIMIT 10;

ALTER ROLE PROFESSORES PASSWORD '123';

-- CREATE ROLE daniel LOGIN PASSWORD '123';
-- DROP ROLE daniel;
-- CREATE ROLE daniel LOGIN PASSWORD '123' IN ROLE professores;
-- CREATE ROLE daniel LOGIN PASSWORD '123' ROLE professores;

CREATE TABLE TESTE (NOME varchar);

GRANT ALL ON TABLE TESTE TO PROFESSORES;

CREATE ROLE DANIEL LOGIN PASSWORD '123';

CREATE ROLE DANIEL LOGIN PASSWORD '123' IN ROLE PROFESSORES;

REVOKE PROFESSORES FROM DANIEL;